### ISSUE TITLE
HEX

### ISSUE THREAD

**Issue by White-Rabbit-Scientific** [dalegambill/CsharpTerminal#2]
The addition of hexadecimal sending and receiving would also be great. I have hacked your SendLine function a little and it can send hex as follows, and this works to send the hex bytes:

```
public void SendLine(string aString)
    {
      try
      {
        if (comPort.IsOpen)
        {
            //comPort.Write(aString);
            byte[] bytestosend = { 0x40, 0x40, 0x40, 0x40 };
            comPort.Write(bytestosend, 0, bytestosend.Length);
        }
      }
      catch (Exception exp)
      {
        Debug.Print(exp.Message);
      }
    }
```

**Comment by dalegambill** [comment]
I want this utility to handle lines of text only.  A terminal that will handle other types of data has many more considerations, and should be a separate project.
