### ISSUE TITLE
Timeout exceptions being thrown

### ISSUE THREAD

**Issue by White-Rabbit-Scientific** [dalegambill/CsharpTerminal#3]
Hi again, I have been playing with your code for a while and it is great, but I have found what I think is a bug. I find that I am getting exceptions after the port is opened as follows: 

```
Exception thrown: 'System.TimeoutException' in System.dll
The operation has timed out.
```
If I change the `comPort.ReadTimeout = 500;` to `comPort.ReadTimeout = 5000;` then the exceptions are thrown a low less frequently. 

Any thoughts? 

Thanks.

**Comment by dalegambill** [comment]
Hi, Rob.  What you are seeing is abnormal behavior, and anything you do to comPort.ReadTimout will only obscure the real problem, even if you set comPort.ReadTimout to SerialPort.InfiniteTimeout. Note that comPort.ReadLine() expects text lines only.  I am guessing your data is not text lines only.

**Comment by White-Rabbit-Scientific** [comment]
Btw, there is a spelling typo in this method:  (...Recevied...)

`private void DataReceviedHandler(object sender, SerialDataReceivedEventArgs e)`
